-- 089_standard_nda_template.sql
-- Replace the platform default NDA with the lawyer-drafted "Pitchey Standard NDA".
-- Placeholders use {{token}} syntax, substituted at render/sign time:
--   date, disclosing_party_name, disclosing_party_address,
--   recipient_name, recipient_address, project_name
-- Idempotent: updates the existing is_default row; inserts one if none exists.

UPDATE nda_templates
SET name = 'Pitchey Standard NDA',
    description = 'Platform standard Non-Disclosure Agreement (lawyer-drafted, Irish law). Fields auto-filled per pitch and signer.',
    template_content = $NDA$NON-DISCLOSURE AGREEMENT
DATE: 	{{date}}
PARTIES:
{{disclosing_party_name}} of {{disclosing_party_address}} ("Disclosing Party"); and
{{recipient_name}} of {{recipient_address}} ("Recipient").
BACKGROUND:
The Disclosing Party has agreed to disclose certain Confidential Information to the Recipient and in consideration thereof the Recipient has agreed to treat the same and all other Confidential Information relating to the Project as confidential on the terms and conditions set out in this Agreement.
AGREEMENT:
Definitions and Interpretation
In this Agreement the following words and expressions shall have the following meanings:
"Confidential Information" means (i) all and any information and material (including any copies or other material or information incorporating all or part any such information or material or referring to the same) disclosed directly or indirectly by the Disclosing Party or on its behalf to the Recipient (whether before or after the date of this Agreement) by any and all means, methods and formats (whether written, electronic or oral), including any information or material relating to the Disclosing Party's systems, operations, opportunities, business plans, intentions, market opportunities, know-how, trade secrets, Intellectual Property Rights, personnel, research, costs, prices, finances and business affairs, and including all scripts, footage, finances, plans, fees and budgets and creative and business matters relating to the production and development of audiovisual works and other programming matters and including the fact that the parties are working together in relation to the Purpose and (ii) without prejudice to the generality of the foregoing, all information relating to the Project (including, but not limited to, plots, stories, characters, dialogue, show budgets, salaries, development plans, marketing plans and surveys, costs and other financial information), its financiers and production partners and their affairs, howsoever that information is obtained by the Recipient;
"Intellectual Property Rights" means any and all intellectual property rights of any nature whatsoever throughout the world and for the full duration of any and all intellectual property protection afforded to the same including, without limitation, all patents, registered trade marks and service marks, registered designs and any and all applications for registration of any of the same wheresoever made and unregistered trade marks and service marks, unregistered designs, design right and copyright;
"Permitted Recipients" shall be as defined in Clause 3.1;
"Project" means a television series currently entitled "{{project_name}}"; and
"Purpose" means the specific purpose for which the Recipient has received the Confidential Information from the Disclosing Party of the Project, as such purpose shall be determined solely by the Disclosing Party.
Any reference to a "person" herein includes a reference to a body corporate, association or partnership and a reference to that person's successors, licensees and permitted assignees.
Any reference to the singular shall be deemed where necessary to include the plural and visa versa.
In the interpretation of this Agreement the phrases "other", "including" and "in particular" shall not limit the generality of any following words or be construed as being limited to the same class as the following words where a wider construction is possible.
Obligations
In consideration of the disclosure of the Disclosing Party’s Confidential Information to the Recipient the Recipient agrees:
to use the Confidential Information only in relation to the Purpose;
to keep the Confidential Information at all times strictly confidential and not to use in any manner that is detrimental to Disclosing Party’s interests or disclose the Confidential Information to any person other than a Permitted Recipient in accordance with Clause 3 below and to use all reasonable endeavours in accordance with Clause 2.1.3 below to prevent its unauthorised disclosure;
to take appropriate measures to safeguard the Confidential Information, including but not limited to password protecting computers and mobile devices which carry the Confidential Information and (without prejudice to Recipient’s obligations hereunder) to exercise in relation to the Confidential Information no lesser security measures and degree of care than the Recipient applies to Recipient’s own confidential information which the Recipient warrants will be adequate to prevent any unauthorised disclosure; and
to make only such copies or reproductions of the Confidential Information as is strictly necessary to fulfil the Purpose and to keep all Confidential Information (including any and all copies, reproductions, images, documents, computer files or other materials incorporating or referring to any of the Confidential Information) separate from all other documents and materials and in a secure place.
to notify the Disclosing Party immediately upon the Recipient's discovery or suspicion of any unauthorised disclosure of Confidential Information, in any form, including that which may result in the Confidential Information being released or otherwise duplicated or transferred outside the control of the Recipient (including without limitation, through an electronic hack). Upon the Recipient's discovery of any such unauthorised disclosure of Confidential Information, the Recipient agrees to cooperate with the Disclosing Party to regain possession of the Confidential Information and prevent its further unauthorised use and/or dissemination.
Nothing in this Agreement will be construed as a representation or agreement that the Recipient shall be entitled to develop or discuss with third parties any products, concepts, business plans, systems, techniques, Intellectual Property Rights, scripts, footage, finances, plans, fees and budgets and creative and business matters relating to the production and development of audiovisual works and other programming matters or other aspects of the Confidential Information that are similar to, or compete with, the Confidential Information or are otherwise adapted from or around the products, concepts, business plans, systems, techniques, Intellectual Property Rights, scripts, footage, finances, plans, fees and budgets and creative and business matters relating to the production and development of audiovisual works and other programming matters or other aspects of the Confidential Information.
Disclosure of Confidential Information
The Recipient may only disclose the Confidential Information to (i) a third party with the prior written consent of the Disclosing Party (who shall have absolute discretion to withhold such consent); and (ii) Recipient’s professional advisers where it is strictly necessary to achieve the Purpose (collectively “Permitted Recipients”) provided always that the Recipient informs Permitted Recipients of the confidential nature of the Confidential Information prior to making any disclosure.
The Recipient hereby represents, undertakes and warrants that Recipient shall procure that Permitted Recipients shall comply at all times with the terms herein (or materially similar terms) as if they were the Recipient under this Agreement, including without limitation, procuring that, prior to the disclosure of the Confidential Information to the Permitted Recipients, they acknowledge, understand and agree to the remedy provisions in Clause 7.6 of this Agreement as if they were the Recipient under this Agreement.
Excluded Information
The obligations set out in Clause 2 above shall not apply to any Confidential Information that the Recipient can demonstrate:
at the time of this Agreement being entered into was in, or has subsequently come into, the public domain other than as a result of a breach of confidentiality or a breach of this Agreement; and/or
has been lawfully received by the Recipient from a third party (not being a Permitted Recipient) without restriction on its use or disclosure; and/or
was lawfully and independently developed by the Recipient other than as a result of a breach of any duty of confidentiality; and/or
was mandatorily required to be disclosed by any law or by any court or regulatory agency or authority.
Return and destruction of Confidential Information
The Recipient shall promptly (and in any event within five (5) days of receipt of a written request from the Disclosing Party) at the Disclosing Party’s election either (i) return to the Disclosing Party the Confidential Information (including for the avoidance of doubt all documents, copies or other materials that incorporate or refer to the Confidential Information), or (ii) if specifically requested by the Disclosing Party, destroy the same and certify to the Disclosing Party in writing that this has been done promptly upon request.
Duration
The obligations undertaken by the Recipient under this Agreement will be continuing and, in particular, will survive the termination or completion of the Purpose and/or the Project. To the extent the Recipient is legally compelled to disclose such Confidential Information by the valid order of a court of competent jurisdiction, the Recipient shall so notify the Disclosing Party as promptly as practicable (and, if possible, prior to making any disclosure) and shall seek confidential treatment of such information, it being understood that the Recipient will cooperate in protecting against any such disclosure and/or obtaining a protective order narrowing the scope of such disclosure and/or use of the Confidential Information.
General
The Recipient warrants and represents to the Disclosing Party that Recipient is entitled to enter this Agreement and to perform Recipient’s obligations herein.  The Disclosing Party makes no warranty, undertaking or representation about the validity, completeness or accuracy of the Confidential Information.
No right or licence is granted by the Disclosing Party to the Recipient in relation to the Confidential Information except as is strictly required for the fulfilment by the Recipient of the Recipient’s services in connection with the Purpose and the Recipient acknowledges and agrees that Recipient does not have nor shall have any right, title or interest in, over or to any of the Confidential Information.  All rights, title and interest of whatever nature (including all Intellectual Property Rights) in and to the Confidential Information shall at all times as between the parties hereto remain solely and exclusively vested in the Disclosing Party.
This Agreement does not commit either party to enter any proposed venture arising out of the Purpose (or otherwise).
If any provision of this Agreement is held by any competent court or regulatory authority to be void or unenforceable in whole or in part and such provision is not fundamental to the commercial purpose of this Agreement, this Agreement shall continue in force in relation to the unaffected provisions and the remainder of the provision in question and the parties shall negotiate in good faith (a) replacement term(s) for the affected provision in order to achieve as closely as possible the original intentions of the parties.
No failure or delay on the part of either party to this Agreement relating to the exercise of any right, power, privilege or remedy provided under this Agreement shall operate as a waiver of such right, power, privilege or remedy or as a waiver of any proceeding or succeeding breach by the other party of this Agreement.
Both parties acknowledge, understand and agree that damages would not be a reasonable or an adequate remedy for any breach by the Recipient of this Agreement and that any breach by the Recipient thereof shall cause the Disclosing Party is irreparable injury and damage, and the Recipient understands, acknowledges and agrees that the Disclosing Party shall be entitled to seek the remedy of injunction, specific performance and/or other equitable relief for a threatened or actual breach of this Agreement by injunction or otherwise for a threatened or actual breach of this Agreement by the Recipient. The Recipient recognises and confirms that in the event of a breach of this Agreement by the Disclosing Party, the damages, if any, caused to the Recipient are not irreparable or sufficient to entitle the Recipient to injunctive or equitable relief. Consequently, the Recipient’s rights and remedies hereunder shall be limited to the right, if any, to recover money damages in an action at law and in no event shall the Recipient have any right in such event to enjoin or restrain the production, distribution, exploitation, advertising, promotion or publicity of the Purpose or the Project or any element thereof.
The Recipient hereby indemnifies (and agrees to keep indemnified) the Disclosing Party and its successors in title, licensees, assigns, directors, shareholders, employees and agents indemnified from and against any and all loss, claims, costs (including legal fees), damages, liabilities and expenses which the Disclosing Party (or any of its successors in title, licensees, assigns, directors, shareholders, employees and agents) may suffer by any reason of any breach or alleged breach by the Recipient of its obligations under this Agreement.
This Agreement may be executed in counterparts each of which when executed and delivered is an original, but the counterparts together shall constitute the same document.
This Agreement contains the full and complete understanding between the parties and supersedes all prior arrangements and understandings whether written or oral appertaining to the subject matter of this Agreement and may not be varied except by written agreement signed by the parties.
The Recipient agrees that this Agreement may be freely assigned and licensed by the Disclosing Party in whole or in part to any third party. The Recipient is not entitled (without the prior written consent of the Disclosing Party) to assign, transfer, sub-contract, sub-licence or otherwise dispose of the benefit or the burden of this Agreement.
This Agreement is governed by and construed in accordance with Irish Law and the parties submit to the exclusive jurisdiction of the courts of Ireland.
IN WITNESS of which the parties hereto have signed this Agreement on the date appearing at the head of this Agreement.
SIGNED by
……………………………………
{{recipient_name}}
SIGNED for and on behalf of
{{disclosing_party_name}} – Disclosing Party
……………………………………
This NDA has been provided by Pitchey Ltd solely as a template for use between the parties named herein. Pitchey Ltd is not a party to this agreement, and each party acknowledges that they are entering into this agreement in their personal or business capacity, and not on behalf of Pitchey Ltd.
Each party is advised to seek independent legal advice prior to signing. Pitchey Ltd accepts no liability for the drafting, interpretation, enforceability, breach, or legal effect of this agreement.$NDA$,
    variables = '["date","disclosing_party_name","disclosing_party_address","recipient_name","recipient_address","project_name"]'::jsonb,
    is_default = true,
    updated_at = NOW()
WHERE is_default = true;

INSERT INTO nda_templates (name, description, template_content, variables, is_default, created_at, updated_at)
SELECT 'Pitchey Standard NDA',
       'Platform standard Non-Disclosure Agreement (lawyer-drafted, Irish law). Fields auto-filled per pitch and signer.',
       $NDA$NON-DISCLOSURE AGREEMENT
DATE: 	{{date}}
PARTIES:
{{disclosing_party_name}} of {{disclosing_party_address}} ("Disclosing Party"); and
{{recipient_name}} of {{recipient_address}} ("Recipient").
BACKGROUND:
The Disclosing Party has agreed to disclose certain Confidential Information to the Recipient and in consideration thereof the Recipient has agreed to treat the same and all other Confidential Information relating to the Project as confidential on the terms and conditions set out in this Agreement.
AGREEMENT:
Definitions and Interpretation
In this Agreement the following words and expressions shall have the following meanings:
"Confidential Information" means (i) all and any information and material (including any copies or other material or information incorporating all or part any such information or material or referring to the same) disclosed directly or indirectly by the Disclosing Party or on its behalf to the Recipient (whether before or after the date of this Agreement) by any and all means, methods and formats (whether written, electronic or oral), including any information or material relating to the Disclosing Party's systems, operations, opportunities, business plans, intentions, market opportunities, know-how, trade secrets, Intellectual Property Rights, personnel, research, costs, prices, finances and business affairs, and including all scripts, footage, finances, plans, fees and budgets and creative and business matters relating to the production and development of audiovisual works and other programming matters and including the fact that the parties are working together in relation to the Purpose and (ii) without prejudice to the generality of the foregoing, all information relating to the Project (including, but not limited to, plots, stories, characters, dialogue, show budgets, salaries, development plans, marketing plans and surveys, costs and other financial information), its financiers and production partners and their affairs, howsoever that information is obtained by the Recipient;
"Intellectual Property Rights" means any and all intellectual property rights of any nature whatsoever throughout the world and for the full duration of any and all intellectual property protection afforded to the same including, without limitation, all patents, registered trade marks and service marks, registered designs and any and all applications for registration of any of the same wheresoever made and unregistered trade marks and service marks, unregistered designs, design right and copyright;
"Permitted Recipients" shall be as defined in Clause 3.1;
"Project" means a television series currently entitled "{{project_name}}"; and
"Purpose" means the specific purpose for which the Recipient has received the Confidential Information from the Disclosing Party of the Project, as such purpose shall be determined solely by the Disclosing Party.
Any reference to a "person" herein includes a reference to a body corporate, association or partnership and a reference to that person's successors, licensees and permitted assignees.
Any reference to the singular shall be deemed where necessary to include the plural and visa versa.
In the interpretation of this Agreement the phrases "other", "including" and "in particular" shall not limit the generality of any following words or be construed as being limited to the same class as the following words where a wider construction is possible.
Obligations
In consideration of the disclosure of the Disclosing Party’s Confidential Information to the Recipient the Recipient agrees:
to use the Confidential Information only in relation to the Purpose;
to keep the Confidential Information at all times strictly confidential and not to use in any manner that is detrimental to Disclosing Party’s interests or disclose the Confidential Information to any person other than a Permitted Recipient in accordance with Clause 3 below and to use all reasonable endeavours in accordance with Clause 2.1.3 below to prevent its unauthorised disclosure;
to take appropriate measures to safeguard the Confidential Information, including but not limited to password protecting computers and mobile devices which carry the Confidential Information and (without prejudice to Recipient’s obligations hereunder) to exercise in relation to the Confidential Information no lesser security measures and degree of care than the Recipient applies to Recipient’s own confidential information which the Recipient warrants will be adequate to prevent any unauthorised disclosure; and
to make only such copies or reproductions of the Confidential Information as is strictly necessary to fulfil the Purpose and to keep all Confidential Information (including any and all copies, reproductions, images, documents, computer files or other materials incorporating or referring to any of the Confidential Information) separate from all other documents and materials and in a secure place.
to notify the Disclosing Party immediately upon the Recipient's discovery or suspicion of any unauthorised disclosure of Confidential Information, in any form, including that which may result in the Confidential Information being released or otherwise duplicated or transferred outside the control of the Recipient (including without limitation, through an electronic hack). Upon the Recipient's discovery of any such unauthorised disclosure of Confidential Information, the Recipient agrees to cooperate with the Disclosing Party to regain possession of the Confidential Information and prevent its further unauthorised use and/or dissemination.
Nothing in this Agreement will be construed as a representation or agreement that the Recipient shall be entitled to develop or discuss with third parties any products, concepts, business plans, systems, techniques, Intellectual Property Rights, scripts, footage, finances, plans, fees and budgets and creative and business matters relating to the production and development of audiovisual works and other programming matters or other aspects of the Confidential Information that are similar to, or compete with, the Confidential Information or are otherwise adapted from or around the products, concepts, business plans, systems, techniques, Intellectual Property Rights, scripts, footage, finances, plans, fees and budgets and creative and business matters relating to the production and development of audiovisual works and other programming matters or other aspects of the Confidential Information.
Disclosure of Confidential Information
The Recipient may only disclose the Confidential Information to (i) a third party with the prior written consent of the Disclosing Party (who shall have absolute discretion to withhold such consent); and (ii) Recipient’s professional advisers where it is strictly necessary to achieve the Purpose (collectively “Permitted Recipients”) provided always that the Recipient informs Permitted Recipients of the confidential nature of the Confidential Information prior to making any disclosure.
The Recipient hereby represents, undertakes and warrants that Recipient shall procure that Permitted Recipients shall comply at all times with the terms herein (or materially similar terms) as if they were the Recipient under this Agreement, including without limitation, procuring that, prior to the disclosure of the Confidential Information to the Permitted Recipients, they acknowledge, understand and agree to the remedy provisions in Clause 7.6 of this Agreement as if they were the Recipient under this Agreement.
Excluded Information
The obligations set out in Clause 2 above shall not apply to any Confidential Information that the Recipient can demonstrate:
at the time of this Agreement being entered into was in, or has subsequently come into, the public domain other than as a result of a breach of confidentiality or a breach of this Agreement; and/or
has been lawfully received by the Recipient from a third party (not being a Permitted Recipient) without restriction on its use or disclosure; and/or
was lawfully and independently developed by the Recipient other than as a result of a breach of any duty of confidentiality; and/or
was mandatorily required to be disclosed by any law or by any court or regulatory agency or authority.
Return and destruction of Confidential Information
The Recipient shall promptly (and in any event within five (5) days of receipt of a written request from the Disclosing Party) at the Disclosing Party’s election either (i) return to the Disclosing Party the Confidential Information (including for the avoidance of doubt all documents, copies or other materials that incorporate or refer to the Confidential Information), or (ii) if specifically requested by the Disclosing Party, destroy the same and certify to the Disclosing Party in writing that this has been done promptly upon request.
Duration
The obligations undertaken by the Recipient under this Agreement will be continuing and, in particular, will survive the termination or completion of the Purpose and/or the Project. To the extent the Recipient is legally compelled to disclose such Confidential Information by the valid order of a court of competent jurisdiction, the Recipient shall so notify the Disclosing Party as promptly as practicable (and, if possible, prior to making any disclosure) and shall seek confidential treatment of such information, it being understood that the Recipient will cooperate in protecting against any such disclosure and/or obtaining a protective order narrowing the scope of such disclosure and/or use of the Confidential Information.
General
The Recipient warrants and represents to the Disclosing Party that Recipient is entitled to enter this Agreement and to perform Recipient’s obligations herein.  The Disclosing Party makes no warranty, undertaking or representation about the validity, completeness or accuracy of the Confidential Information.
No right or licence is granted by the Disclosing Party to the Recipient in relation to the Confidential Information except as is strictly required for the fulfilment by the Recipient of the Recipient’s services in connection with the Purpose and the Recipient acknowledges and agrees that Recipient does not have nor shall have any right, title or interest in, over or to any of the Confidential Information.  All rights, title and interest of whatever nature (including all Intellectual Property Rights) in and to the Confidential Information shall at all times as between the parties hereto remain solely and exclusively vested in the Disclosing Party.
This Agreement does not commit either party to enter any proposed venture arising out of the Purpose (or otherwise).
If any provision of this Agreement is held by any competent court or regulatory authority to be void or unenforceable in whole or in part and such provision is not fundamental to the commercial purpose of this Agreement, this Agreement shall continue in force in relation to the unaffected provisions and the remainder of the provision in question and the parties shall negotiate in good faith (a) replacement term(s) for the affected provision in order to achieve as closely as possible the original intentions of the parties.
No failure or delay on the part of either party to this Agreement relating to the exercise of any right, power, privilege or remedy provided under this Agreement shall operate as a waiver of such right, power, privilege or remedy or as a waiver of any proceeding or succeeding breach by the other party of this Agreement.
Both parties acknowledge, understand and agree that damages would not be a reasonable or an adequate remedy for any breach by the Recipient of this Agreement and that any breach by the Recipient thereof shall cause the Disclosing Party is irreparable injury and damage, and the Recipient understands, acknowledges and agrees that the Disclosing Party shall be entitled to seek the remedy of injunction, specific performance and/or other equitable relief for a threatened or actual breach of this Agreement by injunction or otherwise for a threatened or actual breach of this Agreement by the Recipient. The Recipient recognises and confirms that in the event of a breach of this Agreement by the Disclosing Party, the damages, if any, caused to the Recipient are not irreparable or sufficient to entitle the Recipient to injunctive or equitable relief. Consequently, the Recipient’s rights and remedies hereunder shall be limited to the right, if any, to recover money damages in an action at law and in no event shall the Recipient have any right in such event to enjoin or restrain the production, distribution, exploitation, advertising, promotion or publicity of the Purpose or the Project or any element thereof.
The Recipient hereby indemnifies (and agrees to keep indemnified) the Disclosing Party and its successors in title, licensees, assigns, directors, shareholders, employees and agents indemnified from and against any and all loss, claims, costs (including legal fees), damages, liabilities and expenses which the Disclosing Party (or any of its successors in title, licensees, assigns, directors, shareholders, employees and agents) may suffer by any reason of any breach or alleged breach by the Recipient of its obligations under this Agreement.
This Agreement may be executed in counterparts each of which when executed and delivered is an original, but the counterparts together shall constitute the same document.
This Agreement contains the full and complete understanding between the parties and supersedes all prior arrangements and understandings whether written or oral appertaining to the subject matter of this Agreement and may not be varied except by written agreement signed by the parties.
The Recipient agrees that this Agreement may be freely assigned and licensed by the Disclosing Party in whole or in part to any third party. The Recipient is not entitled (without the prior written consent of the Disclosing Party) to assign, transfer, sub-contract, sub-licence or otherwise dispose of the benefit or the burden of this Agreement.
This Agreement is governed by and construed in accordance with Irish Law and the parties submit to the exclusive jurisdiction of the courts of Ireland.
IN WITNESS of which the parties hereto have signed this Agreement on the date appearing at the head of this Agreement.
SIGNED by
……………………………………
{{recipient_name}}
SIGNED for and on behalf of
{{disclosing_party_name}} – Disclosing Party
……………………………………
This NDA has been provided by Pitchey Ltd solely as a template for use between the parties named herein. Pitchey Ltd is not a party to this agreement, and each party acknowledges that they are entering into this agreement in their personal or business capacity, and not on behalf of Pitchey Ltd.
Each party is advised to seek independent legal advice prior to signing. Pitchey Ltd accepts no liability for the drafting, interpretation, enforceability, breach, or legal effect of this agreement.$NDA$,
       '["date","disclosing_party_name","disclosing_party_address","recipient_name","recipient_address","project_name"]'::jsonb,
       true, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM nda_templates WHERE is_default = true);
